- Duriso.xcodeproj/project.pbxproj
- Duriso/Model/Board/BoardModel.swift
- Duriso/Model/Guideline/GuidelineModel.swift
- Duriso/View/Board/BoardTableViewCell.swift
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/CategoryCell.swift
- Duriso/View/Board/PostViewController.swift
- Duriso/View/Board/PostingViewController.swift
- Duriso/ViewModel/Board/BoardViewModel.swift
Feat: 셀버튼 이벤트 생성
Design: 셀 클릭시 UI생성
<br><br>
PostingViewController 생성
PostingViewController UI작업
BoradViewController TableView Touch Event 생성
<br><br>
PostingViewController
UIImage == nil일때 Layout변경
<br><br>
#7 
#40 
- Close #이슈번호
<br><br>
> Feat: 셀버튼 이벤트 생성 / Design: 셀 클릭시 UI생성

- Duriso.xcodeproj/project.pbxproj
- Duriso/Common/FirebaseFirestoreManager.swift
- Duriso/Info.plist
- Duriso/Model/OfflineMap/LocationModel.swift
- Duriso/View/MainTabBarViewController.swift
- Duriso/View/OfflineMap/OfflineMapViewController.swift
- Duriso/View/OfflineMap/OfflineViewController.swift
- Duriso/ViewModel/OfflineMap/OfflineMapViewModel.swift
Chore: SPM - MapLibre 추가
Feat: OfflineMap 화면 구현
Feat: OfflineMap 개발용 MainTabBar 항목 추가
Feat: LocationModel 구현
Feat: OfflineMapViewModel 구현
Feat: OfflineViewController 구현
Feat: OfflineMapViewController 구현
Chore: 정확한 위치,사진 저장 권한 요청 메시지 작성
Comment: requestButton 비활성화
Feat: FirebaseFiresotreManager 구현
<br><br>
SPM - MapLibre 추가
OfflineMap 화면 구현
OfflineMap 개발용 MainTabBar 항목 추가
LocationModel 구현
OfflineMapViewModel 구현
OfflineViewController 구현
OfflineMapViewController 구현
정확한 위치,사진 저장 권한 요청 메시지 작성
requestButton 비활성화
FirebaseFiresotreManager 구현
<br><br>
OfflineMap Poi 구현 필요
<br><br>
- #5 
<br><br>
> feature/offlinemap to develop PR

- Duriso/View/Board/PostViewController.swift
- Duriso/View/Board/PostingViewController.swift
Design: safeAreaLayoutGuide, Alert버튼 위치변경
<br><br>
Design: safeAreaLayoutGuide, Alert버튼 위치변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: safeAreaLayoutGuide, Alert버튼 위치변경

- Duriso/Model/Board/BoardModel.swift
- Duriso/View/Board/BoardCollectionViewCell.swift
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Guideline/GuidelineViewController.swift
- Duriso/View/MyPage/MyPageViewController.swift
Design: Layout & Constraints 수정
<br><br>
Layout & Constraints 수정
<br><br>
<br><br>
- #3 #6 #7 
<br><br>
> Design: Layout & Constraints 수정

- Duriso/Model/Board/BoardModel.swift
- Duriso/View/Board/BoardCollectionViewCell.swift
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/PostingViewController.swift
- Duriso/ViewModel/Board/BoardViewModel.swift
Feat: 게시글 수정, 삭제, 신고1회 기능 추가
<br><br>
동일 닉네임 게시글 수정
동일 닉네임 게시글 삭제
동일 닉네임 신고 1회 가능
<br><br>
<br><br>
#7 
- Close #이슈번호
<br><br>
> Feat: 게시글 수정, 삭제, 신고1회 기능 추가

- Duriso.xcodeproj/project.pbxproj
- Duriso/View/Board/BoardViewController.swift
Fix: pbxproj 중복파일 제거 및 오타 수정
<br><br>
pbxproj 중복파일 제거 및 오타 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: pbxproj 중복파일 제거 및 오타 수정

- Duriso/ViewModel/Login/LoginViewModel.swift
Fix: 로그인 실패 시 로그인버튼 미작동 오류 해결
<br><br>
로그인 실패 시 로그인버튼 미작동 오류 해결
<br><br>
로그인 실패 에러메세지 확인 필요
<br><br>
#74 
- Close #이슈번호
<br><br>
> Fix: 로그인 실패 시 로그인버튼 미작동 오류 해결

- Duriso/View/Board/BoardTableViewCell.swift
Fix: 주소 미표기 해결
<br><br>
주소 미표기 해결
numberOfLines 삭제
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: 주소 미표기 해결

- Duriso/Info.plist
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/PostViewController.swift
- Duriso/View/Board/PostingViewController.swift
- Duriso/View/Guideline/GuidelineViewController.swift
- Duriso/View/OnlineMap/BottomsheetView/EmergencyWrittingViewController.swift
- Duriso/ViewModel/Guideline/GuidelineViewModel.swift
Camera, Library 접근제어 Alert 표기
게시글 nickName -> uuid 변경
<br><br>
Camera, Library 접근제어 Alert 표기
게시글 nickName -> uuid 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Feat: Camera, Library 접근제어 Alert 표기, 게시글 nickName -> uuid 변경

- Duriso/Info.plist
- Duriso/View/Board/PostingViewController.swift
카메라 Alert변경
Alert내용수정
userNickName추가
<br><br>
카메라 Alert변경
Alert내용수정
userNickName추가
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Feat: 카메라 Alert변경, 내용수정, userNickName추가

- Duriso.xcodeproj/project.pbxproj
- Duriso/View/LoginView/SignUpViewController.swift
- Duriso/View/LoginView/SignUptableViewCell.swift
- Duriso/View/MyPage/ChangePasswordViewController.swift
- Duriso/View/MyPage/LegalNoticeViewController.swift
- Duriso/View/MyPage/ModifyInformationViewController.swift
Feat: 회원가입 진행 시 이용약관 확인 구현
<br><br>
회원가입 진행 시 이용약관 확인 구현
<br><br>
이용약관에 하나라도 체크가 안되어 있을 경우 저장버튼 눌러도 반응없음
<br><br>
#74 
- Close #이슈번호
<br><br>
> Feat: 회원가입 진행 시 이용약관 확인 구현

- Duriso/View/MyPage/MyPageViewController.swift
Design: 마이페이지 문의 메일 추가
Feat: 로그아웃 구현
<br><br>
마이페이지 문의 메일 추가
로그아웃 구현
<br><br>
<br><br>
#3 #74
- Close #이슈번호
<br><br>
> Design: 마이페이지 문의 메일 추가, 로그아웃 구현

- Duriso.xcodeproj/project.pbxproj
Remove: 카메라 권한 요청 메시지 중복 삭제
Chore: Build Number 갱신
<br><br>
카메라 권한 요청 메시지 중복 삭제
Build Number 갱신
<br><br>
- 카메라 권한 요청 메시지 중복 관련(Project Setting -> Build Setting -> Info.plist Values 중복)
<br><br>
- Close #이슈번호
<br><br>
> hotfix to develop PR

- Duriso/View/Board/PostViewController.swift
- Duriso/View/Board/PostingViewController.swift
Feat: 좋아요 기능 Firebase저장
TextView 내용수정
<br><br>
좋아요 기능 Firebase저장
TextView 내용수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Feat: 좋아요 기능 Firebase저장

- Duriso/View/LoginView/LoginViewController.swift
- Duriso/View/MyPage/MyPageViewController.swift
Feat: 자동 로그인 구현
<br><br>
자동 로그인 구현
<br><br>
<br><br>
#74 
- Close #이슈번호
<br><br>
> Feat: 자동 로그인 구현

- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/PostingViewController.swift
Feat: 차단기능 추가
<br><br>
차단기능 추가
<br><br>
상대방 차단시 글 안보이기
차단시 리프레시 한번 해줘야함
<br><br>
- Close #이슈번호
<br><br>
> Feat: 차단기능 추가

- Duriso.xcodeproj/project.pbxproj
Chore: Build Number 갱신
<br><br>
- Build Number 갱신
- 배포 심사 제출
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Chore: Build Number 갱신

- Duriso/View/Board/BoardViewController.swift
최신순 반대로 나오는 버그 수정
<br><br>
최신순 반대로 나오는 버그 수정
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Fix: 최신순 반대로 나오는 버그 수정

- Duriso.xcodeproj/project.pbxproj
- Duriso/View/Board/BoardCollectionViewCell.swift
- Duriso/View/Board/BoardTableViewCell.swift
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/EditPostViewController.swift
- Duriso/View/Board/UserPostViewController.swift
- Duriso/View/Board/WritingViewController.swift
Refactor: 변수명 클래스명 변경
Feat: Image 킹피셔 적용, 유저nil일시 Alert
<br><br>
Refactor: 변수명 클래스명 변경
Feat: Image 킹피셔 적용, 유저nil일시 Alert
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Refactor: 변수명 클래스명 변경/Feat: Image 킹피셔 적용, 유저nil일시 Alert

- Duriso.xcodeproj/project.pbxproj
- Duriso/View/Board/BoardViewController.swift
- Duriso/View/Board/UserPostViewController.swift
- Duriso/View/LoginView/LoginViewController.swift
- Duriso/View/MyPage/MuteTableViewCell.swift
- Duriso/View/MyPage/MuteViewController.swift
- Duriso/View/MyPage/MyPageViewController.swift
- Duriso/ViewModel/Login/SignUpViewModel.swift
- Duriso/ViewModel/MyPage/MuteViewModel.swift
- Duriso/ViewModel/MyPage/MyPageViewModel.swift
Feat: 비회원으로 둘러보기 구현
Feat: 회원 탈퇴 구현
Fix: 자동 로그인 후 로그아웃 시 로그인 화면으로 돌아가지 않던 오류 수정
<br><br>
비회원으로 둘러보기 구현
회원 탈퇴 구현
자동 로그인 후 로그아웃 시 로그인 화면으로 돌아가지 않던 오류 수정
<br><br>
<br><br>
#69 #74 
- Close #이슈번호
<br><br>
> Feat: 비회원으로 둘러보기, 회원 탈퇴 구현, 자동 로그인 오류 수정

- Duriso/View/Board/BoardTableViewCell.swift
Design: Cell image 없으면 Label위치 변경
<br><br>
Design: Cell image 없으면 Label위치 변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: Cell image 없으면 Label위치 변경

- Duriso/View/Board/WritingViewController.swift
Feat: 제목, 내용이 nil일시 Alert 띄우기
<br><br>
Feat: 제목, 내용이 nil일시 Alert 띄우기
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Feat: 제목, 내용이 nil일시 Alert 띄우기

- Duriso/Model/Board/BoardModel.swift
- Duriso/Model/Guideline/GuidelineModel.swift
- Duriso/View/Guideline/GuidelineTableViewCell.swift
- Duriso/View/Guideline/GuidelineViewController.swift
- Duriso/ViewModel/Guideline/GuidelineTableViewModel.swift
Design: 행동요령 UI변경
<br><br>
행동요령 UI변경
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Design: 행동요령 UI변경

- README.md
Docs: README.md 파일 작성
<br><br>
README.md 파일 작성
<br><br>
<br><br>
- Close #이슈번호
<br><br>
> Docs: README.md 파일 작성

- Duriso.xcodeproj/project.pbxproj
- Duriso/Base.lproj/LaunchScreen.storyboard
Design: LaunchScreen 사이즈 변경
Chore: App Version 갱신(V 1.0.3(1))
<br><br>
LaunchScreen 사이즈 변경
App Version 갱신(V 1.0.3(1))
<br><br>
V. 1.0.3
<br><br>
- Close #이슈번호
<br><br>
> Release (V. 1.0.3)

- Duriso.xcodeproj/project.pbxproj
Chore: App Version 갱신(V 1.1.0 (1))
<br><br>
App Version 갱신(V 1.1.0 (1))
<br><br>
V. 1.1.0
<br><br>
- Close #이슈번호
<br><br>
> Release (V. 1.1.0)

- Duriso/View/LoginView/LoginViewController.swift
- Duriso/ViewModel/Login/LoginViewModel.swift
- Fix: 자동로그인 오류 수정 및 로그인 검증 로직 수정
- Fix Issue
#129
#130
<br><br>
1. LoginViewController.swift
주요 변경사항:
1. 자동 로그인 로직 개선
- Auth.auth().currentUser 체크 추가
- 자동 로그인 시 사용자 상태 확인 로직 강화
2. 로그인 버튼 이벤트 처리 방식 변경
- 기존: bind(to: viewModel.loginTap)
- 변경: subscribe(onNext:) 사용하여 직접 처리
3. 로그인 성공 처리 로직 개선
- 자동 로그인 상태 저장을 로그인 성공 시점으로 이동
- 체크박스 상태에 따른 조건부 저장 추가
- 메인 화면 전환 로직 단순화
2. LoginViewModel.swift
주요 변경사항:
1. 입력값 검증 로직 추가
- 이메일/비밀번호 빈 값 검사
- 이메일 형식 유효성 검사 (isValidEmail 함수 추가)
2. 에러 처리 개선
- Firebase 에러 메시지 통합 및 보안 강화
- 구체적인 에러 메시지 대신 일반적인 메시지로 통일
- 새로운 에러 케이스 추가 (userDisabled, tooManyRequests 등)
3. 에러 메시지 개선
- 보안을 위해 구체적인 에러 원인 대신 일반적인 메시지 사용
- "이메일 또는 비밀번호가 올바르지 않습니다"로 통일
- 네트워크 오류, 계정 비활성화 등 특수 케이스에 대한 메시지 추가
<br><br>
<br><br>
- Close #129
- Close #130 
<br><br>
> feature/login to develop PR

- Duriso/Base.lproj/LaunchScreen.storyboard
- Fix: LaunchScreen 안뜨는 오류 해결
- Fix Issue
#137 
<br><br>
ImageView로 AppLogo 적용
<br><br>
<br><br>
- Close #137 
<br><br>
> feature/modify-UI to develop PR

- Duriso.xcodeproj/project.pbxproj
- Chore: Build Phases 스크립트 수정 (Setup Firebase Environment GoogleService-Info.plist)
<br><br>
- Development/Production 설정 수정
<br><br>
<br><br>
- 
<br><br>
> Chore: Build Phases 스크립트 수정 (Setup Firebase Environment GoogleService-Info.plist)

- Duriso.xcodeproj/project.pbxproj
- Duriso/Info.plist
- Chore: AppStore Connect 앱 암호화 사용 여부 설정값 추가
- Chore: App Version 갱신 (V 1.1.1 (1))
<br><br>
- AppStore Connect 앱 암호화 사용 여부 설정값 추가
- App Version 갱신 (V 1.1.1 (1))
<br><br>
- V 1.1.1
<br><br>
- Close #이슈번호
<br><br>
> Release (V. 1.1.1)
